PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/urls.py
from django.urls import path
from . import views

app_name = "AEROLINEA"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:vuelo_id>', views.vuelo, name="vuelo"),
    path('vuelo_alta', views.vuelo_alta, name="vuelo_alta"),
    path('<int:vuelo_id>/vuelo_modificar', views.vuelo_modificar, name="vuelo_modificar"),
    path('<int:vuelo_id>/vuelo_eliminar', views.vuelo_eliminar, name="vuelo_eliminar"),
    path('<int:vuelo_id>/reserva', views.reserva, name="reserva")
]

PROJECTCLASE11/PROJECTCLASE11/ANIONUEVO/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index")
]

PROJECTCLASE11/PROJECTCLASE11/PROJECTCLASE11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ANIONUEVO/', include("ANIONUEVO.urls")),
    path('TAREAS/', include("TAREAS.urls")),
    path('AEROLINEA/', include("AEROLINEA.urls"))
]

PROJECTCLASE11/PROJECTCLASE11/TAREAS/urls.py
from django.urls import path
from . import views

app_name = "TAREAS"
urlpatterns = [
    path('', views.index, name="index"),
    path('agregar', views.agregar, name="agregar")
]

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/models.py
from django.db import models

# Create your models here.
class Aeropuerto(models.Model):
    codigo = models.CharField(max_length=3)
    ciudad = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.ciudad} ({self.codigo})"
        
class Vuelo(models.Model):
    origen = models.ForeignKey(Aeropuerto, on_delete=models.CASCADE, related_name="salidas")
    destino = models.ForeignKey(Aeropuerto, on_delete=models.CASCADE, related_name="arribos")
    duracion = models.IntegerField()

    def __str__(self):
        return f"Vuelo #{self.id}: {self.origen} hacia {self.destino}"

class Pasajero(models.Model):
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    vuelos = models.ManyToManyField(Vuelo, blank=True, related_name="pasajeros")

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

PROJECTCLASE11/PROJECTCLASE11/ANIONUEVO/models.py
from django.db import models

# Create your models here.

PROJECTCLASE11/PROJECTCLASE11/TAREAS/models.py
from django.db import models

# Create your models here.

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/forms.py
from django import forms
from .models import Vuelo

class FormVueloCustom(forms.ModelForm):
    #campos del modelo
    class Meta:
        model = Vuelo
        fields = ('origen', 'destino', 'duracion')

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Vuelo, Pasajero
from .forms import FormVueloCustom

# Create your views here.
def index(request):
    return render(request,"vuelos/index.html", {
        "lista_vuelos": Vuelo.objects.all()
    })

def vuelo(request, vuelo_id):
    vuelo = Vuelo.objects.get(id=vuelo_id)
    pasajeros = vuelo.pasajeros.all()
    no_son_pasajeros = Pasajero.objects.exclude(vuelos=vuelo).all()
    return render(request, "vuelos/vuelo.html", {
        "vuelo": vuelo,
        "pasajeros": pasajeros,
        "no_son_pasajeros": no_son_pasajeros
    })


def vuelo_alta(request):
    #VueloForm = modelform_factory(Vuelo, fields=("origen", "destino", "duracion"))
    if request.method == "POST":
        form = FormVueloCustom(request.POST)
        if form.is_valid():
            form.save()
        return render(request,"vuelos/index.html", {
            "lista_vuelos": Vuelo.objects.all()
        })
    else:
        form = FormVueloCustom()
        return render(request, "vuelos/vuelo_alta.html", {
            "form": form
        })


def vuelo_modificar(request, vuelo_id):
    un_vuelo = get_object_or_404(Vuelo, id=vuelo_id)
    
    if request.method == "POST":     
        form = FormVueloCustom(request.POST, instance = un_vuelo) 
        if form.is_valid():
            form.save()
            return render(request,"vuelos/index.html", {
                "lista_vuelos": Vuelo.objects.all()
            })
    else:
        form = FormVueloCustom(instance = un_vuelo)
        return render(request, 'vuelos/vuelo_modificar.html', {
            "un_vuelo": un_vuelo,
            "form": form
        })


def vuelo_eliminar(request, vuelo_id):
    un_vuelo = get_object_or_404(Vuelo, id=vuelo_id)
    un_vuelo.delete()
    return render(request,"vuelos/index.html", {
        "lista_vuelos": Vuelo.objects.all()
    })


def reserva(request, vuelo_id):
    if request.method == "POST":
        vuelo = Vuelo.objects.get(pk=vuelo_id)
        pasajero_id = int(request.POST["pasajero"])
        pasajero = Pasajero.objects.get(pk=pasajero_id)
        pasajero.vuelos.add(vuelo)
        return HttpResponseRedirect(reverse("AEROLINEA:vuelo", args=(vuelo.id,)))

PROJECTCLASE11/PROJECTCLASE11/ANIONUEVO/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    ahora = datetime.datetime.now()
    return render(request, "anionuevo/index.html", {
        ##"anionuevo": ahora.month == 1 and ahora.day == 1
        "anionuevo": True
    })

PROJECTCLASE11/PROJECTCLASE11/TAREAS/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

## necesitamos tener las tareas en sesiones
# tareas = ["bañarse", "vestirse", "prepararcosas", "salir", "tomar colectivo"]
class FormAltaTarea(forms.Form):
    tarea = forms.CharField(label="Nueva Tarea")

# Create your views here.
def index(request):
    if "tareas" not in request.session:
        request.session["tareas"] = []
    return render(request, "tareas/index.html", {
        'tareas': request.session["tareas"]
        })

def agregar(request):

    if request.method == "POST":
        form = FormAltaTarea(request.POST)
        if form.is_valid():
            tarea = form.cleaned_data["tarea"]
            request.session["tareas"] += [tarea]
            return HttpResponseRedirect(reverse("TAREAS:index"))
        else:
            return render(request, "tareas/agregar.html", {
                "formulario_alta_tarea": form
            })
    else:
        return render(request, "tareas/agregar.html", {
            "formulario_alta_tarea": FormAltaTarea()
        })

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/templates/vuelos/index.html
{% extends "vuelos/layout.html" %}
{% block body %}
    <h1>Vuelos</h1>
    <ul>
        {% for un_vuelo in lista_vuelos %}
            <li><a href="{% url 'AEROLINEA:vuelo' un_vuelo.id %}">Ver Vuelo #{{un_vuelo.id}}</a> <a href="{% url 'AEROLINEA:vuelo_modificar' un_vuelo.id %}">Editar</a> <a href="{% url 'AEROLINEA:vuelo_eliminar' un_vuelo.id %}">Eliminar</a>: {{un_vuelo.origen}} hacia {{un_vuelo.destino}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'AEROLINEA:vuelo_alta'%}">Alta de Vuelo</a>
{% endblock %}

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/templates/vuelos/layout.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Vuelos</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/templates/vuelos/vuelo.html
{% extends "vuelos/layout.html" %}
{% block body %}
<h2>Vuelo</h2>
<h3>Lista de Pasajeros</h3>
<ul>
    {% for un_pasajero in pasajeros %}
        <li>{{ un_pasajero }}</li>
    {% empty %}
        <li>No hay pasajeros registrados.</li>
    {% endfor %}
</ul>
<a href="{% url 'AEROLINEA:index' %}">Volver a la lista</a>
<h3>Reserva</h3>
<form action="{% url 'AEROLINEA:reserva' vuelo.id %}" method="post">
    {% csrf_token %}
    <select name="pasajero" id="">
        {% for un_pasajero in no_son_pasajeros %}
            <option value="{{ un_pasajero.id }}">{{ un_pasajero }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="RESERVAR">
</form>
{% endblock %}

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/templates/vuelos/vuelo_alta.html
{% extends "vuelos/layout.html" %}
{% block body %}
<h3>Alta de Vuelo</h3>
<form action="{% url 'AEROLINEA:vuelo_alta' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="GUARDAR">
</form>
{% endblock %}

PROJECTCLASE11/PROJECTCLASE11/AEROLINEA/templates/vuelos/vuelo_modificar.html
{% extends "vuelos/layout.html" %}
{% block body %}
<h3>Modificar Vuelo</h3>
<form action="{% url 'AEROLINEA:vuelo_modificar' un_vuelo.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="GUARDAR">
</form>
{% endblock %}

PROJECTCLASE11/PROJECTCLASE11/ANIONUEVO/templates/anionuevo/index.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>¿Es año nuevo hoy?</title>
    </head>
    <body>
        <!--AQUI ES DONDE PUEDO TRABAJAR CON LOGICA DENTRO DE UN TEMPLATE-->
        {% if anionuevo %}
            <h1>SI</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

PROJECTCLASE11/PROJECTCLASE11/TAREAS/templates/tareas/agregar.html
{% extends "tareas/layout.html" %}
{% block body %}
<h1>Alta de Tarea</h1>
<form action="{% url 'TAREAS:agregar' %}" method="post">
    {% csrf_token %}
    {{ formulario_alta_tarea }}
    <input type="submit" value="Guardar">
</form>
<div class="acciones">
    <a href="{% url 'TAREAS:index' %}">Volver a la Lista de Tareas</a>
</div>
{% endblock %}

PROJECTCLASE11/PROJECTCLASE11/TAREAS/templates/tareas/index.html
{% extends "tareas/layout.html" %}
{% block body %}
    {% for una_tarea in tareas %}
        <li>{{ una_tarea }}</li>
    {% endfor %}
    <div class="acciones">
        <a href="{% url 'TAREAS:agregar' %}">Agregar una nueva Tarea</a>
    </div>
{% endblock %}

PROJECTCLASE11/PROJECTCLASE11/TAREAS/templates/tareas/layout.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Listado de Tareas</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>